services:
  bookingproject.api:
    image: ${DOCKER_REGISTRY-}bookingproject.api
    build:
      context: .
      dockerfile: BookingProject.API/Dockerfile
    ports:
      - 8080:8080
    environment:
      - ConnectionStrings__DefaultConnection=Server=docker_sql_server;Database=Booking;User
        Id=SA;Password=abc.1234!;MultipleActiveResultSets=true;TrustServerCertificate=True
    depends_on:
      - docker_sql_server
  docker_sql_server:
    build:
      context: .
      dockerfile: BookingProject.API/db.Dockerfile
    ports:
      - 1433:1433
    volumes:
      - db_data:/var/opt/mssql
volumes:
  db_data: 
